enable-magisk-update = true # set this to false if you do not want to receive up

# you can use rvmm-config-gen to generate a config

[YouTube]
build-mode = "both"
version = "latest"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
arch = "all"

[Music]
build-mode = "both"
version = "latest"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
arch = "all"

[Music-ReX]
app-name = "Music"
build-mode = "both"
version = "latest"
patches-source = "YT-Advanced/ReX-patches"
integrations-source = "YT-Advanced/ReX-integrations"
rv-brand = "ReX"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
arch = "all"

[YouTube-ReX]
app-name = "YouTube"
build-mode = "both"
version = "latest"
patches-source = "YT-Advanced/ReX-patches"
integrations-source = "YT-Advanced/ReX-integrations"
rv-brand = "ReX"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
arch = "all"

[Twitter]
build-mode = "apk"
version = "latest"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.twitter.android"
# uptodown-dlurl = "https://twitter.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter"
arch = "all"

[Twitch]
build-mode = "apk"
version = "latest"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/tv.twitch.android.app"
uptodown-dlurl = "https://twitch.en.uptodown.com/android"
arch = "all"

[Instagram]
enabled = true
version = "latest"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.instagram.android"
uptodown-dlurl = "https://instagram.en.uptodown.com/android"
arch = "arm64-v8a"
