enable-magisk-update = true # set this to false if you do not want to receive up

# you can use rvmm-config-gen to generate a config

[YouTube]
build-mode = "both"
excluded-patches = ""
included-patches = ""
version = "latest"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
arch = "all"

[Music]
build-mode = "both"
version = "latest"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
arch = "both"

[Twitter]
build-mode = "apk"
version = "latest"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.twitter.android"
# uptodown-dlurl = "https://twitter.en.uptodown.com/android"
arch = "all"

[Twitch]
enabled = true
version = "latest"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/tv.twitch.android.app"
uptodown-dlurl = "https://twitch.en.uptodown.com/android"
arch = "all"

[TikTok]
enabled = true
version = "latest"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.zhiliaoapp.musically"
uptodown-dlurl = "https://tiktok.en.uptodown.com/android"
# arch = "armeabi-v7a, arm64-v8a"

[Reddit]
enabled = true
version = "latest"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.reddit.frontpage"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"

[Instagram]
enabled = true
version = "latest"
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/messenger/"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.instagram.android"
#uptodown-dlurl = "https://instagram.en.uptodown.com/android"
arch = "all"

[Music-ReX]
enabled = true
app-name = "Music"
version = "latest"
patches-source = "YT-Advanced/ReX-patches"
integrations-source = "YT-Advanced/ReX-integrations"
rv-brand = "ReX"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
arch = "both"


[YouTube-ReX]
enabled = true
app-name = "YouTube"
version = "latest"
patches-source = "YT-Advanced/ReX-patches"
integrations-source = "YT-Advanced/ReX-integrations"
rv-brand = "ReX"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
arch = "all"
