enable-magisk-update = true # set this to false if you do not want to receive up

# you can use rvmm-config-gen to generate a config

[YouTube]
build-mode = "both"
version = "latest"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"

[Music]
build-mode = "both"
version = "latest"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"

[Music-ReX]
app-name = "Music"
build-mode = "both"
version = "latest"
patches-source = "YT-Advanced/ReX-patches"
integrations-source = "YT-Advanced/ReX-integrations"
rv-brand = "ReX"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"

[YouTube-ReX]
app-name = "YouTube"
build-mode = "both"
version = "latest"
patches-source = "YT-Advanced/ReX-patches"
integrations-source = "YT-Advanced/ReX-integrations"
rv-brand = "ReX"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"

[Twitter]
build-mode = "apk"
version = "latest"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter"

[Twitch]
build-mode = "apk"
version = "latest"
apkmirror-dlurl = "https://www.apkmirror.com/apk/twitch-interactive-inc"

[TikTok]
build-mode = "apk"
version = "latest"
uptodown-dlurl = "https://tiktok.en.uptodown.com/android"

[Reddit]
build-mode = "apk"
version = "latest"
patches-source = "YT-Advanced/ReX-patches"
integrations-source = "YT-Advanced/ReX-integrations"
rv-brand = "ReX"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"

[Messenger]
build-mode = "apk"
version = "latest"
uptodown-dlurl = "https://messenger.en.uptodown.com/android"

[Facebook]
build-mode = "apk"
version = "latest"
uptodown-dlurl = "https://facebook.en.uptodown.com/android"

[Instagram]
build-mode = "apk"
version = "latest"
uptodown-dlurl = "https://instagram.en.uptodown.com/android"

[Spotify]
build-mode = "apk"
version = "latest"
uptodown-dlurl = "https://spotify.en.uptodown.com/android"

[Tasker]
build-mode = "apk"
version = "latest"
uptodown-dlurl = "https://tasker.en.uptodown.com/android"

[Lightroom]
build-mode = "apk"
version = "latest"
uptodown-dlurl = "https://adobe-lightroom-mobile.en.uptodown.com/android"
