enable-magisk-update = true # set this to false if you do not want to receive up

# you can use rvmm-config-gen to generate a config

[YouTube]
build-mode = "both"
version = "latest"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"

[Music]
build-mode = "both"
version = "latest"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"

[Music-ReX]
app-name = "Music"
build-mode = "both"
version = "latest"
patches-source = "YT-Advanced/ReX-patches"
integrations-source = "YT-Advanced/ReX-integrations"
rv-brand = "ReX"
apkmirror-dlurl = "https://youtube-music.en.uptodown.com/android"

[YouTube-ReX]
app-name = "YouTube"
build-mode = "both"
version = "latest"
patches-source = "YT-Advanced/ReX-patches"
integrations-source = "YT-Advanced/ReX-integrations"
rv-brand = "ReX"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
