enable-magisk-update = true # set this to false if you do not want to receive up

# you can use rvmm-config-gen to generate a config

[YouTube]
build-mode = "both"
version = "auto"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"

[Music]
build-mode = "both"
version = "auto"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"

[Music-ReX]
app-name = "Music"
build-mode = "both"
version = "latest"
patches-source = "anddea/revanced-patches/tree/dev"
integrations-source = "anddea/revanced-integrations/tree/dev"
rv-brand = "ReX"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
excluded-patches = ""
included-patches = "'Custom branding icon YouTube Music' 'Custom branding name YouTube Music'"

[YouTube-ReX]
app-name = "YouTube"
build-mode = "both"
version = "19.11.38"
patches-source = "anddea/revanced-patches/tree/dev"
integrations-source = "anddea/revanced-integrations/tree/dev"
rv-brand = "ReX"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
excluded-patches = "'Shorts overlay buttons'"
included-patches = "'Custom branding icon YouTube' 'Custom branding name YouTube'"
